### ISSUE TITLE
Creacion de los Script

### ISSUE THREAD

**Issue by J-Pinos3** [eoncorpec/pdf_to_excel_sc#31]
Se deben crear los scripts para ejecutarlos y obtener la información de los pdf.

**Comment by richiprieto** [comment]
El script 3 columnas el momento de la ejecución está cortando la primera letra del contador, representante legal e ident_representante. Ver las imágenes a continuación.
![Screenshot_2024-05-17_10-49-19](https://github.com/eoncorpec/pdf_to_excel_sc/assets/7146095/8df2f94b-7590-4734-8f0f-1183fcaa85f1)
![Screenshot_2024-05-17_10-49-01](https://github.com/eoncorpec/pdf_to_excel_sc/assets/7146095/d3aa4232-5d00-4c81-95e5-eadeba51037c)
