### ISSUE TITLE
Error en el encabezado archivo doc_economica1

### ISSUE THREAD

**Issue by richiprieto** [eoncorpec/pdf_to_excel_sc#4]
En el archivo del encabezado existe un pequeño error porque se repite RAZÓN SOCIAL más no el nombre de la empresa.
![Screenshot from 2024-02-16 22-02-57](https://github.com/eoncorpec/pdf_to_excel_sc/assets/7146095/296e4637-dfe2-4389-babb-c515b4483088)

Para el caso que estaba probando es corporación favorita 
![Screenshot from 2024-02-16 22-05-03](https://github.com/eoncorpec/pdf_to_excel_sc/assets/7146095/7c62a53b-b209-48cd-a470-8bacaa986e9b)

**Comment by J-Pinos3** [comment]
Estos errores se corrigen en el issue principal acumulando la información y formateando los datos del contador y cabecera

**Comment by J-Pinos3** [comment]
Estos errores se corrigen en el issue principal acumulando la información y formateando los datos del contador y cabecera
