### ISSUE TITLE
Nueva distribución de archivo de salida doc_economica1

### ISSUE THREAD

**Issue by richiprieto** [eoncorpec/pdf_to_excel_sc#5]
La información del encabezado esta bien de lo que pude observar, sin embargo, hay que cambiar la presentación de los datos.
Actualmente esta asi 
![Screenshot from 2024-02-16 22-07-02](https://github.com/eoncorpec/pdf_to_excel_sc/assets/7146095/b22b2e65-31f6-47ae-8073-aaa6e6553fd8)

Necesito que se organice de forma vertical de esta manera:
![Screenshot from 2024-02-16 22-11-48](https://github.com/eoncorpec/pdf_to_excel_sc/assets/7146095/6632b15c-6f00-49ea-9c89-f428a2f758c7)

Los nombres de las columnas serían las siguientes

RAZÓN SOCIAL | DIRECCIÓN | EXPEDIENTE | RUC | AÑO | FORMULARIO | FECHA DE LA JUNTA QUE APRUEBA | ESTADOS DE SITUACION FINANCIERA | REPRESENTANTE LEGAL | IDENT. REPRESENTANTE LEGAL | CONTADOR | IDENT. CONTADOR | COD. CONTADOR

**Comment by J-Pinos3** [comment]
Estos errores se corrigen en el issue principal acumulando la información y formateando los datos del contador y cabecera
