### ISSUE TITLE
Estandarización de carpeta Input

### ISSUE THREAD

**Issue by richiprieto** [eoncorpec/pdf_to_excel_sc#6]
La carpeta input va a tener múltiples archivos mezclados, se enviará por correo los archivos.

La forma en la que podemos identificar a qué empresa pertenece cada archivo será mediante el número de expediente que se encuentra resaltado en la siguiente imagen. El número siempre estará en la misma posición, inmediatamente después de la palabra "DocEconomica", para el caso del ejemplo es 384, ese será nuestro identificador.

![Screenshot from 2024-02-16 22-17-25](https://github.com/eoncorpec/pdf_to_excel_sc/assets/7146095/4a7fa862-fb66-4fd8-a588-6ebdded2bcfe)

Desde ahora la carpeta input que vamos a usar es la que se envía por correo, no hacerle ninguna modificación.
**No cambiar de nombre al archivo, llamarlo directamente con el nombre original tal y como coloco en el ejemplo**

![Screenshot from 2024-02-16 22-18-39](https://github.com/eoncorpec/pdf_to_excel_sc/assets/7146095/b810451a-f9b0-47d5-8280-c3fdeeb306c2)

**Comment by J-Pinos3** [comment]
Estos errores se corrigen en el issue principal acumulando la información y formateando los datos del contador y cabecera
