### ISSUE TITLE
Agregar un campo en la hoja Datos de doc_económica1

### ISSUE THREAD

**Issue by richiprieto** [eoncorpec/pdf_to_excel_sc#7]
Necesito que en el sheet "Datos", se agregue el campo **EXPEDIENTE** con el número de expediente de la empresa y **ANIO** con el año que contiene la información del pdf. en este caso a modo de ejemplo que estábamos usando info de corporación favorita, sería el número de expediente 384. 
La referencia está en la imagen, el resto de campos no cambian, solo aumentamos esos campos (columnas) al inicio.

**  Ignorar esta imagen, la correcta esta en el siguiente comentario**
![Screenshot from 2024-02-16 22-25-44](https://github.com/eoncorpec/pdf_to_excel_sc/assets/7146095/ccf8fa4a-6631-4bed-ab12-dc2f9532eb5c)

**Comment by richiprieto** [comment]
![Screenshot from 2024-02-16 23-08-27](https://github.com/eoncorpec/pdf_to_excel_sc/assets/7146095/21f75893-9986-4abb-b7d2-4691412c12d9)

**Comment by J-Pinos3** [comment]
Estos errores se corrigen en el issue principal acumulando la información y formateando los datos del contador y cabecera
