### ISSUE TITLE
Unificación en un solo archivo de ESTADO DE SITUACIÓN FINANCIERA

### ISSUE THREAD

**Issue by richiprieto** [eoncorpec/pdf_to_excel_sc#8]
La idea del proyecto es crear un software que pueda extraer cualquier archivo PDF que tenga estados de situación financiera, ya que los campos son siempre los mismos.

![Screenshot from 2024-02-16 22-42-39](https://github.com/eoncorpec/pdf_to_excel_sc/assets/7146095/f423aa5c-d433-41a6-88ae-f456ee2ac8e9)

Vamos a iniciar editando el cuaderno que voy a subir y esta en esta dirección.

**No borrar los archivos anteriormente trabajados, el código es reutilizable**
![Screenshot from 2024-02-16 22-46-36](https://github.com/eoncorpec/pdf_to_excel_sc/assets/7146095/8d959827-923f-4bfc-a069-2ccb6ca56e4e)

La idea es que el archivo de salida sea único y que cada ejecución este vaya haciendo un append de datos como filas, el archivo de datos quedaría algo similar es este de ejemplo, obviamente con todas las columnas del archivo PDF.

![Screenshot from 2024-02-16 23-04-40](https://github.com/eoncorpec/pdf_to_excel_sc/assets/7146095/556deac3-8c26-4566-987e-2a238416cf16)

**Notar que se aumentaron dos columnas una de EXPEDIENTE, donde consta el número de expediente y la otra ANIO, donde esta la información de año del documento extraido**

**Comment by J-Pinos3** [comment]
Este principal acumula la información y formatea los datos del contador y cabecera, aún se deben añadir más archivos
